### ISSUE TITLE
What does idle mean?

### ISSUE THREAD

**Issue by Morgyn** [JocysCom/FocusLogger#1]
Hi, When the focus is taken from the game the focus is shown as "idle", what does this  mean?

**Comment by source011** [comment]
+1

**Comment by EJocys** [comment]
An "Idle" process is a "System Idle Process", a Windows OS process with a priority of 0. The CPU switches to this process when it has nothing to do, ie. i.e. waiting for another process to add the job to the queue. If the CPU has absolutely nothing to do, the "Idle" process will use 100% of the CPU (Defined as "Percentage of time the process is Idle" in Task Manger).
