### ISSUE TITLE
uninstalling focusLogger

### ISSUE THREAD

**Issue by zaxtiss** [JocysCom/FocusLogger#12]
i'm trying to help my buddy un install this.
can you tell me where the files install with this? program files doesn't show anything.
did it use the appData folders?

**Comment by EJocys** [comment]
Focus Logger is a portable app that doesn't actually save any settings. It is just a single portable executable. Just delete the `JocysCom.FocusLogger.exe` file and maybe the shortcut to it, and that's it.
