### ISSUE TITLE
What is the 2nd 'M' column?

### ISSUE THREAD

**Issue by fdwr** [JocysCom/FocusLogger#7]
'M'ouse and 'K'eyboard are obvious. 'A' maybe stands for application, but the 2nd 'M' is a mystery 🤔❔...

![image](https://github.com/JocysCom/FocusLogger/assets/1809166/514992a2-f05b-4616-af87-6814bb213dc5)

**Comment by fdwr** [comment]
Aah, digging into the resources, the little faded blue and gray right arrow ➡ is actually not a faded blue and gray right arrow, but rather a text edit control 📝. Digging further into the code, it appears to be linked to the `_HasCaret` field.

Suggestion then: Rename the 2nd "M" to "C" for caret or "T" for text?

Thanks for the tool, as I'm hoping to catch focus thieves in the future. Computer\HKEY_CURRENT_USER\Control Panel\Desktop\ForegroundLockTimeout doesn't do the trick 🤔.

**Comment by EJocys** [comment]
@fdwr 

Thank you for suggestion. Updated release page with the download to the new version:

https://github.com/JocysCom/FocusLogger/releases

2023-06-15 - Version 1.1.12

- Fixed caret column title from "M" to "C".
- Increased caret icon size a bit.
- Disabled resizing of A,M,K,C for better access to tooltip.
- Updated shared classes.

**Comment by fdwr** [comment]
Wow, so fast. I wasn't expecting any changes for weeks/months, if any 😅. Also, sorry I just noticed even the old version had tooltips too - I guess I didn't hover the mouse over them long enough 😑. Thanks Evaldas.
